#!/usr/bin/env bash
# WEB STACK DEBUGGING
if [[ -p $(which nginx) ]]; then
    sudo chown $USER:$USER /etc/nginx/sites-available/default
    $server_cnf="
    server {
	listen 80;
	server_name _;
	root /var/www/html;
	
	location / {
	   try_files $url $url/ =404;
	}
    }"
    echo "$server_cnf" > /etc/nginx/sites-available/default
else
    sudo apt-get update && upgrade
    sudo apt-get -y install nginx
sudo systemctl restart nginx
