#!/usr/bin/env bash
# WEB STACK DEBUGGING
install_nginx(){
    sudo apt-get update && upgrade
    sudo apt-get -y install nginx
}
if [[-n $(which nginx) ]]; then
    sudo apt-get uninstall nginx
    sudo apt-get autoremove nginx
    install_nginx
else
    install_nginx
fi
