#!/usr/bin/env bash
# WEB STACK DEBUGGING
install_nginx(){
    sudo apt-get update && upgrade
    sudo apt-get -y install nginx
}
if [[ -n $(which nginx) ]]; then
    sudo apt-get purge --auto-remove nginx
    chmod 777 /var/www /etc/nginx
    rm -r /var/www /etc/nginx
    install_nginx
else
    install_nginx
fi
